# import

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# read data from excel

In [10]:
# excel
xl = 'stk-2024-07-05.xlsx'

stock_data = pd.read_excel(xl)
stock_data.tail()

Unnamed: 0        date  stock_id  Trading_Volume  Trading_money   open  \
407         407  2024-06-28       919        60450567     1564288528  25.83   
408         408  2024-07-01       919       104525328     2732154338  25.86   
409         409  2024-07-02       919        74441424     1939078004  26.14   
410         410  2024-07-03       919        36864723      961097654  26.13   
411         411  2024-07-04       919        60116599     1568696435  26.12   

       max    min  close  spread  Trading_turnover  
407  25.95  25.80  25.85    0.05             21261  
408  26.27  25.86  26.14    0.29             25849  
409  26.21  25.92  26.00   -0.14             29449  
410  26.17  26.00  26.02    0.02             15362  
411  26.17  26.02  26.03    0.01             18940

# Feedforward Neural Network(前饋神經網路)

# Scale data

In [11]:
# 選擇特徵/數據
x = stock_data[['open', 'max', 'min', 'Trading_Volume']]
y = stock_data['close']

# 特徵縮放
scaler = MinMaxScaler()
x_scaled = scaler.fit_transform(x)

# 切割數據:訓練/測試
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, test_size=0.2, random_state=42)

# Create model

In [12]:
model = Sequential()
model.add(Dense(64, input_dim=x_train.shape[1], activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='linear'))

d:\Projects\python\DS\stock\venv\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


# Compile model

In [13]:
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['accuracy'])

# Fit model

In [14]:
model.fit(x_train, y_train, epochs=50, batch_size=10, validation_split=0.2)

Epoch 1/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.0000e+00 - loss: 431.7780 - val_accuracy: 0.0000e+00 - val_loss: 404.2963
Epoch 2/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 390.2589 - val_accuracy: 0.0000e+00 - val_loss: 350.4328
Epoch 3/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 327.1508 - val_accuracy: 0.0000e+00 - val_loss: 247.5018
Epoch 4/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 209.3936 - val_accuracy: 0.0000e+00 - val_loss: 113.4330
Epoch 5/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 85.4695 - val_accuracy: 0.0000e+00 - val_loss: 25.2701
Epoch 6/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 20.7072 - val_accuracy: 0.0000e+00 - val_loss: 13.2316
Epoch 7/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 10.6483 - val_accuracy: 0.0000e+00 - val_loss: 11.5530
Epoch 8/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s

# Review model

In [15]:
loss = model.evaluate(x_test, y_test)
loss

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.0164 


[0.01728729158639908, 0.0]

# To predict

In [16]:
print(f"input:{x_test}")
result = model.predict(x_test)

for i in range(10):
    print(f"預測:{result[i]}, 實際:{y_test.iloc[i]}")

input:[[0.59392945 0.58886159 0.58746949 0.2972709 ]
 [0.14191961 0.15315315 0.14890155 0.00450059]
 [0.47005742 0.46519247 0.46216436 0.13311088]
 [0.17555373 0.17035217 0.15703824 0.00862806]
 [0.6021329  0.5978706  0.59235151 0.25982891]
 [0.81296144 0.81244881 0.80553295 0.06807988]
 [0.53814602 0.54054054 0.53539463 0.06787414]
 [0.35110747 0.34971335 0.34825061 0.00500044]
 [0.49876948 0.5045045  0.50284784 0.04956288]
 [0.45447088 0.45454545 0.44914565 0.09983046]
 [0.17965546 0.17936118 0.18063466 0.00717993]
 [0.5561936  0.55446355 0.55899105 0.07159084]
 [0.76210008 0.75921376 0.72742067 0.27153072]
 [0.30598852 0.31122031 0.29861676 0.00350195]
 [0.23297785 0.22768223 0.21969081 0.00545863]
 [0.1657096  0.16871417 0.16517494 0.00293343]
 [0.60295324 0.6036036  0.60618389 0.07184754]
 [0.6242822  0.61834562 0.6086249  0.18711639]
 [0.61197703 0.60687961 0.60943857 0.06432873]
 [0.25758819 0.28255528 0.26362897 0.00631727]
 [0.87612797 0.87714988 0.86493084 0.12828452]
 [0.007